### ISSUE TITLE
Tomb Raider I from GOG + OpenLara fails on the Steam Deck

### ISSUE THREAD

**Issue by nnunix** [legluondunet/MyLittleLutrisScripts#137]
Hello,

This script does not really work on the steam deck. 
for some reason the 7z command fails. 
I tried to give permissions to Lutris using Flatseal but still this is a no go. 

attached is the debug output. I deleted the GOG download sections as it contained authentication tokens in there.

I am happy to help in anything you need to solve the issue

thanks,
[
[lutris_log.txt](https://github.com/legluondunet/MyLittleLutrisScripts/files/9396157/lutris_log.txt)
](url)

**Comment by legluondunet** [comment]
Hello @nnunix , I don't own a Steam Deck (not yet...).
But I can try to help you.
Is 7z installed on your distribution (Steam OS)?

**Comment by nnunix** [comment]
Thanks for the reply.

7zip is installed, and I can run the 7z executable from that location via konsole, but since Lutris is installed as a flatpak, form the Flathub beta channel, that might be the cause.
I am not sure though as I haven't worked much with flatpak packages. It looks as though Lutris cannot see that 7z executable. 

if somehow you are able to run lutris from flathub, maybe you will be able to reproduce it? 
Let me know if you would like me to try anything on this.

**Comment by tepiloxtl** [comment]
I got the same issue, Lutris in flatpak on Steam Deck, trying GOG + TombATI HD install script. Fails in the same way. 7z is installed in SteamOS

**Comment by tepiloxtl** [comment]
I've had a while to dip my toes into this. Turns out, when you pass system resources into Flatpak, it doesnt get mounted in its respective place (which makes sense, becaue flatpak does provide its own environment, to an extent), but it gets prefixed with `/host`. So in this case, the `7z` script in `cdrtools.zip` has to be modified for Flatpak to point to `/host/usr/lib/p7zip/7z` for it to run. Though this will not work for Lutris installed on bare system, there will have to be some mechanism to detect if we are running in Flatpak or on bare metal. I might look into it more over the weekend still...

**Comment by legluondunet** [comment]
Fixed with commit 1d354fd
