### ISSUE TITLE
The Secret of Monkey Island Special Edition - Source does not exist

### ISSUE THREAD

**Issue by Weldar** [legluondunet/MyLittleLutrisScripts#29]
Full Error Message: Source does not exist: .cache/lutris/installer/the-secret-of-monkey-island-special-edition/app

The Installer downloads and configures the wine prefix, but throws this error before asking for an installation file. This is for the GOG installer.

**Comment by legluondunet** [comment]
Hello @Weldar , thank you for your report.

It's a known Lutris bug, you have to wait until new version will be provided by your Linux distribution
or
use last git version
or try this:

1°) Download "The Secret of Monkey Island Special Edition" directly from GOG
2°) launch Lutris, go to "import games" and disconnect from GOG
3°) if already installed, uninstall "The Secret of Monkey Island Special Edition" from Lutris
4°) launch again "The Secret of Monkey Island Special Edition" install

If you correctly disconnected from GOG in Lutris parameters, next time you will try to install a GOG game, Lutris will ask you for the GOG setup file on your local hard drive instead of download it automatically from GOG servers.

**Comment by Weldar** [comment]
Well don't I feel foolish, I even have the git version.... I just haven't synced it in awhile. 
I appreciate you taking the time to respond. Do you have a tip jar?

**Comment by legluondunet** [comment]
I haven't a tip jar for the moment, but I appreciate your offer.

**Comment by legluondunet** [comment]
New Lutris version should be available for your distribution.
After updating, you should not be able to reproduce this bug.
