### ISSUE TITLE
Star Wars: Knights of the Old Republic 21:9 3440x1440

### ISSUE THREAD

**Issue by weesom** [legluondunet/MyLittleLutrisScripts#78]
Hi,
i'd like to play SW KotOR on a 21:9 3440x1440 monitor (if it's possible)
Also would be happy to help with the patching if provided with some instructions

**Comment by legluondunet** [comment]
Hello,
did you look at this page:
https://www.wsgf.org/article/star-wars-knights-old-republic

**Comment by legluondunet** [comment]
Hello,
I just updated my script (fixed some issues) and I decided to not support other resolution than 1920x1080.
Because at the moment I'm writing this lines, I have only computer screens with HD resolution.
And there are all needed files and mods for 1920x1080 resolution on internet, but not yet for other resolutions or it's not complete.
This game  is in opengl so I can not use a graphic wrapper to support different resolutions neither.

However I found two interesting links for you:
- https://www.gog.com/forum/star_wars_knights_of_the_old_republic_series/sw_kotor_1_high_resolution_fix_219_3440x14402560x1080_and_probably_all_other
- https://www.nexusmods.com/kotor/mods/1358

I hope you will find what you search on this links.
